"""Generate (or check) docs/package-index.md from package metadata.

The index is derived from ``pyproject.toml`` records and metapackage
dependencies — never hand-maintained — so it cannot drift from the authoritative
lifecycle and curation data. Experimental packages are listed as
source-install-only and are never claimed to be on PyPI.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent))

from repo_packages import (  # noqa: E402
    ROOT,
    PackageRecord,
    load_package_records,
)

INDEX_PATH = ROOT / "docs" / "package-index.md"

HEADER = """\
# Package index

<!-- Generated by scripts/generate_package_index.py from pyproject.toml metadata
     and metapackage dependencies. Do not edit by hand; run
     `python scripts/generate_package_index.py` to refresh. -->

Lifecycle status is declared per package in `[tool.ce_plugin_repo] status`.
See `docs/plugin-lifecycle.md` for status definitions and the promotion process.
"""


def _plugin_line(record: PackageRecord, root: Path) -> str:
    return (
        f"- `{record.distribution_name}` {record.version} — family `{record.family}`, "
        f"`{record.relative_path(root)}`"
    )


def render_index(records: list[PackageRecord], root: Path = ROOT) -> str:
    metas = [r for r in records if r.package_type == "meta"]
    plugins = [r for r in records if r.package_type == "plugin"]
    curated = [r for r in plugins if r.status == "mature" and r.in_metapackage]
    standalone = [r for r in plugins if r.status == "mature" and not r.in_metapackage]
    experimental = [r for r in plugins if r.status == "experimental"]
    deprecated = [r for r in plugins if r.status == "deprecated"]

    lines: list[str] = [HEADER]

    lines.append("## Metapackages\n")
    lines.append(
        "Installable from PyPI once released. Family metapackages contain only\n"
        "curated mature plugins; the umbrella metapackage aggregates the families.\n"
    )
    for record in sorted(metas, key=lambda r: r.distribution_name):
        lines.append(f"- `{record.distribution_name}` {record.version}")
    lines.append("")

    lines.append("## Mature curated plugins\n")
    lines.append(
        "Mature plugins selected into a family metapackage (recommended default\n"
        "installation). Install individually with `pip install <name>`.\n"
    )
    if curated:
        for record in sorted(curated, key=lambda r: r.distribution_name):
            memberships = ", ".join(f"`{m}`" for m in record.metapackage_memberships)
            lines.append(f"{_plugin_line(record, root)}, curated in {memberships}")
    else:
        lines.append("- None yet.")
    lines.append("")

    lines.append("## Mature standalone plugins\n")
    lines.append(
        "Mature plugins published to PyPI individually but not part of a\n"
        "metapackage. Install with `pip install <name>`.\n"
    )
    if standalone:
        for record in sorted(standalone, key=lambda r: r.distribution_name):
            lines.append(_plugin_line(record, root))
    else:
        lines.append("- None yet.")
    lines.append("")

    lines.append("## Experimental plugins\n")
    lines.append(
        "Under development or evaluation. **Not published to PyPI** and not part\n"
        "of any metapackage; install from a repository checkout, e.g.\n"
        "`pip install ./packages/<family>/<name>`.\n"
    )
    if experimental:
        for record in sorted(experimental, key=lambda r: r.distribution_name):
            lines.append(_plugin_line(record, root))
    else:
        lines.append("- None.")
    lines.append("")

    lines.append("## Deprecated plugins\n")
    lines.append(
        "No longer recommended and excluded from metapackages and ordinary\n"
        "releases. See each package README for migration guidance.\n"
    )
    if deprecated:
        for record in sorted(deprecated, key=lambda r: r.distribution_name):
            lines.append(_plugin_line(record, root))
    else:
        lines.append("- None.")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or check docs/package-index.md.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed index differs from the generated content.",
    )
    args = parser.parse_args()

    records = load_package_records()
    content = render_index(records)
    if args.check:
        existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if existing != content:
            print(
                "ERROR: docs/package-index.md is stale. Run "
                "`python scripts/generate_package_index.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("Package index is up to date.")
        return 0
    INDEX_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
